// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SharpBizz.Http.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HttpUtils_WriteRequestAsync")]
    [NUnit.Framework.CategoryAttribute("httpSerialization")]
    public partial class HttpUtils_WriteRequestAsyncFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HttpUtils_WriteRequestAsync.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HttpUtils_WriteRequestAsync", "Create a binary serialized version of a given HttpRequestMessage", ProgrammingLanguage.CSharp, new string[] {
                        "httpSerialization"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a simple request message")]
        [NUnit.Framework.TestCaseAttribute("GET", null)]
        [NUnit.Framework.TestCaseAttribute("POST", null)]
        [NUnit.Framework.TestCaseAttribute("PUT", null)]
        [NUnit.Framework.TestCaseAttribute("DELETE", null)]
        [NUnit.Framework.TestCaseAttribute("HEAD", null)]
        [NUnit.Framework.TestCaseAttribute("PATCH", null)]
        [NUnit.Framework.TestCaseAttribute("OPTIONS", null)]
        [NUnit.Framework.TestCaseAttribute("CUSTOM", null)]
        public virtual void WriteASimpleRequestMessage(string method, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a simple request message", exampleTags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("A simple HTTP request is created with \"{0}\", \"http://www.example.com/\" and HTTP v" +
                        "ersion 1 and 1", method), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And(string.Format("The string representation of the stream is a simple request message with \"{0}\", \"" +
                        "http://www.example.com/\" and HTTP version 1 and 1", method), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a simple request message with different types of URLs")]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/", null)]
        [NUnit.Framework.TestCaseAttribute("https://www.example.com/", null)]
        [NUnit.Framework.TestCaseAttribute("http://localhost/", null)]
        [NUnit.Framework.TestCaseAttribute("https://localhost/", null)]
        [NUnit.Framework.TestCaseAttribute("http://192.168.17.1/", null)]
        [NUnit.Framework.TestCaseAttribute("https://192.168.17.1/", null)]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/path", null)]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/path.ext", null)]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/?query=value", null)]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/?query=value&other=123", null)]
        [NUnit.Framework.TestCaseAttribute("http://www.example.com/path with escapes/", null)]
        public virtual void WriteASimpleRequestMessageWithDifferentTypesOfURLs(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a simple request message with different types of URLs", exampleTags);
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given(string.Format("A simple HTTP request is created with \"GET\", \"{0}\" and HTTP version 1 and 1", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.And(string.Format("The string representation of the stream is a simple request message with \"GET\", \"" +
                        "{0}\" and HTTP version 1 and 1", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a simple request message with different HTTP versions")]
        [NUnit.Framework.TestCaseAttribute("1", "1", null)]
        [NUnit.Framework.TestCaseAttribute("1", "0", null)]
        [NUnit.Framework.TestCaseAttribute("1", "7", null)]
        [NUnit.Framework.TestCaseAttribute("2", "0", null)]
        [NUnit.Framework.TestCaseAttribute("0", "9", null)]
        public virtual void WriteASimpleRequestMessageWithDifferentHTTPVersions(string major, string minor, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a simple request message with different HTTP versions", exampleTags);
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given(string.Format("A simple HTTP request is created with \"GET\", \"http://www.example.com/\" and HTTP v" +
                        "ersion {0} and {1}", major, minor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.And(string.Format("The string representation of the stream is a simple request message with \"GET\", \"" +
                        "http://www.example.com/\" and HTTP version {0} and {1}", major, minor), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a simple request message with one content header and no content")]
        [NUnit.Framework.TestCaseAttribute("Content-Disposition", "attachment; filename=\"fname.ext\"", null)]
        [NUnit.Framework.TestCaseAttribute("Content-Location", "/index.htm", null)]
        [NUnit.Framework.TestCaseAttribute("Content-MD5", "Q2hlY2sgSW50ZWdyaXR5IQ==", null)]
        [NUnit.Framework.TestCaseAttribute("Content-Range", "bytes 21010-47021/47022", null)]
        [NUnit.Framework.TestCaseAttribute("Expires", "Thu, 01 Dec 1994 16:00:00 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("Last-Modified", "Tue, 15 Nov 1994 12:45:26 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("Allow", "GET, HEAD, OPTIONS", null)]
        [NUnit.Framework.TestCaseAttribute("Content-Encoding", "gzip, lzha", null)]
        [NUnit.Framework.TestCaseAttribute("Content-Language", "da, en-US, pt-PT, es-ES", null)]
        public virtual void WriteASimpleRequestMessageWithOneContentHeaderAndNoContent(string header, string value, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a simple request message with one content header and no content", exampleTags);
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given(string.Format("A simple request is created with content \"{0}\" with value \"{1}\" and empty string " +
                        "content", header, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
 testRunner.And(string.Format("The string representation of the stream is a simple request with \"{0}\" with value" +
                        " \"{1}\" and plain text content type", header, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a simple request message with one request header and no content")]
        [NUnit.Framework.TestCaseAttribute("Accept-Datetime", "Thu, 31 May 2007 20:35:00 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("Authorization", "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==", null)]
        [NUnit.Framework.TestCaseAttribute("Cache-Control", "no-cache", null)]
        [NUnit.Framework.TestCaseAttribute("Connection", "keep-alive", null)]
        [NUnit.Framework.TestCaseAttribute("Cookie", "$Version=1; Skin=new;", null)]
        [NUnit.Framework.TestCaseAttribute("Date", "Tue, 15 Nov 1994 08:12:31 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("Expect", "100-continue", null)]
        [NUnit.Framework.TestCaseAttribute("From", "user@example.com", null)]
        [NUnit.Framework.TestCaseAttribute("Host", "www.example.com:80", null)]
        [NUnit.Framework.TestCaseAttribute("If-Match", "\"737060cd8c284d8af7ad3082f209582d\"", null)]
        [NUnit.Framework.TestCaseAttribute("If-Modified-Since", "Tue, 15 Nov 1994 08:12:31 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("If-None-Match", "\"737060cd8c284d8af7ad3082f209582d\"", null)]
        [NUnit.Framework.TestCaseAttribute("If-Range", "\"737060cd8c284d8af7ad3082f209582d\"", null)]
        [NUnit.Framework.TestCaseAttribute("If-Unmodified-Since", "Tue, 15 Nov 1994 08:12:31 GMT", null)]
        [NUnit.Framework.TestCaseAttribute("Max-Forwards", "10", null)]
        [NUnit.Framework.TestCaseAttribute("Origin", "http://www.example-social-network.com", null)]
        [NUnit.Framework.TestCaseAttribute("Pragma", "no-cache", null)]
        [NUnit.Framework.TestCaseAttribute("Proxy-Authorization", "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==", null)]
        [NUnit.Framework.TestCaseAttribute("Range", "bytes=500-999", null)]
        [NUnit.Framework.TestCaseAttribute("Referer", "http://en.wikipedia.org/wiki/Main_Page", null)]
        [NUnit.Framework.TestCaseAttribute("Accept", "text/plain, text/html", null)]
        [NUnit.Framework.TestCaseAttribute("Accept-Charset", "utf-8, utf-16, utf-32", null)]
        [NUnit.Framework.TestCaseAttribute("Accept-Encoding", "gzip, deflate", null)]
        [NUnit.Framework.TestCaseAttribute("Accept-Language", "en-US, es-ES, pt-PT", null)]
        [NUnit.Framework.TestCaseAttribute("TE", "trailers, deflate", null)]
        [NUnit.Framework.TestCaseAttribute("Upgrade", "HTTP/2.0, SHTTP/1.3, IRC/6.9, RTA/x11", null)]
        [NUnit.Framework.TestCaseAttribute("User-Agent", "Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/21.0", null)]
        [NUnit.Framework.TestCaseAttribute("Via", "1.0 fred, 1.1 example.com (Apache/1.1)", null)]
        public virtual void WriteASimpleRequestMessageWithOneRequestHeaderAndNoContent(string header, string value, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a simple request message with one request header and no content", exampleTags);
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given(string.Format("A simple request is created with request \"{0}\" with value \"{1}\"", header, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 72
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.And(string.Format("The string representation of the stream is a simple request with \"{0}\" with value" +
                        " \"{1}\"", header, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write a request message with byte array content")]
        public virtual void WriteARequestMessageWithByteArrayContent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write a request message with byte array content", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("A HTTP request is created with byte array content of 100 bytes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.When("The request message is written to a stream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("The stream is not empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
 testRunner.And("The string representation of the stream is a request with a 100 bytes content", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
